package com.google.android.gms.internal.ads;

import android.content.Context;
import android.content.SharedPreferences;
import android.content.SharedPreferences.Editor;
import java.util.List;
import java.util.concurrent.TimeUnit;
import org.json.JSONObject;

@cm
public final class asa
{
  public static final arq<Long> A;
  public static final arq<Boolean> B;
  public static final arq<Boolean> C;
  public static final arq<Boolean> D;
  public static final arq<String> E;
  public static final arq<Integer> F;
  public static final arq<Boolean> G;
  public static final arq<Boolean> H;
  public static final arq<String> I;
  public static final arq<String> J;
  public static final arq<String> K;
  public static final arq<String> L;
  public static final arq<Boolean> M;
  public static final arq<Boolean> N;
  public static final arq<String> O;
  public static final arq<Boolean> P;
  public static final arq<Boolean> Q;
  public static final arq<Integer> R;
  public static final arq<Integer> S;
  public static final arq<Integer> T;
  public static final arq<Integer> U;
  public static final arq<Integer> V;
  public static final arq<Boolean> W;
  public static final arq<Integer> X;
  public static final arq<Boolean> Y;
  public static final arq<Integer> Z;
  public static final arq<String> a;
  public static final arq<Boolean> aA;
  public static final arq<Boolean> aB;
  public static final arq<Boolean> aC;
  public static final arq<Boolean> aD;
  public static final arq<Long> aE;
  public static final arq<Boolean> aF;
  public static final arq<Boolean> aG;
  public static final arq<Long> aH;
  public static final arq<Long> aI;
  public static final arq<Boolean> aJ;
  public static final arq<Long> aK;
  public static final arq<Boolean> aL;
  public static final arq<Boolean> aM;
  public static final arq<Boolean> aN;
  public static final arq<Boolean> aO;
  public static final arq<Long> aP;
  public static final arq<Boolean> aQ;
  public static final arq<Boolean> aR;
  public static final arq<Boolean> aS;
  public static final arq<Boolean> aT;
  public static final arq<Boolean> aU;
  public static final arq<String> aV;
  public static final arq<String> aW;
  public static final arq<Integer> aX;
  public static final arq<Integer> aY;
  public static final arq<Integer> aZ;
  public static final arq<Integer> aa;
  public static final arq<String> ab;
  public static final arq<String> ac;
  public static final arq<Boolean> ad;
  public static final arq<Boolean> ae;
  public static final arq<Boolean> af;
  public static final arq<Long> ag;
  public static final arq<Boolean> ah;
  public static final arq<Boolean> ai;
  public static final arq<Boolean> aj;
  public static final arq<Boolean> ak;
  public static final arq<Boolean> al;
  public static final arq<Boolean> am;
  public static final arq<Boolean> an;
  public static final arq<Boolean> ao;
  public static final arq<Boolean> ap;
  public static final arq<String> aq;
  public static final arq<String> ar;
  public static final arq<Boolean> as;
  public static final arq<Boolean> at;
  public static final arq<String> au;
  public static final arq<Long> av;
  public static final arq<Integer> aw;
  public static final arq<Boolean> ax;
  public static final arq<Boolean> ay;
  public static final arq<Boolean> az;
  public static final arq<Boolean> b;
  public static final arq<Long> bA;
  public static final arq<Long> bB;
  public static final arq<Boolean> bC;
  public static final arq<Long> bD;
  public static final arq<Boolean> bE;
  public static final arq<Boolean> bF;
  public static final arq<Boolean> bG;
  public static final arq<Boolean> bH;
  public static final arq<Boolean> bI;
  public static final arq<Boolean> bJ;
  public static final arq<String> bK;
  public static final arq<Boolean> bL;
  public static final arq<Boolean> bM;
  public static final arq<Boolean> bN;
  public static final arq<Boolean> bO;
  public static final arq<Boolean> bP;
  public static final arq<Boolean> bQ;
  public static final arq<Boolean> bR;
  public static final arq<Boolean> bS;
  public static final arq<String> bT;
  public static final arq<Long> bU;
  public static final arq<Boolean> bV;
  public static final arq<Boolean> bW;
  public static final arq<String> bX;
  public static final arq<String> bY;
  public static final arq<Boolean> bZ;
  public static final arq<String> ba;
  public static final arq<Integer> bb;
  public static final arq<Integer> bc;
  public static final arq<Long> bd;
  public static final arq<Long> be;
  public static final arq<Float> bf;
  public static final arq<Float> bg;
  public static final arq<Boolean> bh;
  public static final arq<Boolean> bi;
  public static final arq<String> bj;
  public static final arq<String> bk;
  public static final arq<Boolean> bl;
  public static final arq<Boolean> bm;
  public static final arq<Long> bn;
  public static final arq<Boolean> bo;
  public static final arq<Boolean> bp;
  public static final arq<Long> bq;
  public static final arq<Boolean> br;
  public static final arq<Boolean> bs;
  public static final arq<Boolean> bt;
  public static final arq<Boolean> bu;
  public static final arq<Long> bv;
  public static final arq<Boolean> bw;
  public static final arq<Boolean> bx;
  public static final arq<Boolean> by;
  public static final arq<Long> bz;
  public static final arq<Boolean> c;
  public static final arq<Long> cA;
  public static final arq<Boolean> cB;
  public static final arq<Boolean> cC;
  public static final arq<Boolean> cD;
  public static final arq<Boolean> cE;
  public static final arq<Boolean> cF;
  public static final arq<Long> cG;
  public static final arq<Boolean> cH;
  public static final arq<Boolean> cI;
  public static final arq<String> cJ;
  public static final arq<Integer> cK;
  public static final arq<Boolean> cL;
  public static final arq<Boolean> cM;
  public static final arq<Boolean> cN;
  public static final arq<Boolean> cO;
  public static final arq<Boolean> cP;
  public static final arq<Boolean> cQ;
  public static final arq<Long> cR;
  public static final arq<String> cS;
  public static final arq<String> cT;
  public static final arq<String> cU;
  public static final arq<String> cV;
  public static final arq<Integer> cW;
  public static final arq<Integer> cX;
  public static final arq<Boolean> cY;
  public static final arq<Boolean> cZ;
  public static final arq<Boolean> ca;
  public static final arq<Boolean> cb;
  public static final arq<Integer> cc;
  public static final arq<Integer> cd;
  public static final arq<String> ce;
  public static final arq<Boolean> cf;
  public static final arq<Boolean> cg;
  public static final arq<Boolean> ch;
  public static final arq<Boolean> ci;
  public static final arq<Boolean> cj;
  public static final arq<Boolean> ck;
  public static final arq<Boolean> cl;
  public static final arq<Boolean> cm;
  public static final arq<Boolean> cn;
  public static final arq<Long> co;
  public static final arq<Integer> cp;
  public static final arq<Integer> cq;
  public static final arq<Long> cr;
  public static final arq<Boolean> cs;
  public static final arq<Long> ct;
  public static final arq<String> cu;
  public static final arq<String> cv;
  public static final arq<String> cw;
  public static final arq<String> cx;
  public static final arq<String> cy;
  public static final arq<Long> cz;
  public static final arq<Boolean> d;
  private static final arq<String> dA;
  private static final arq<Boolean> dB;
  private static final arq<Float> dC;
  private static final arq<String> dD;
  private static final arq<String> dE;
  private static final arq<Boolean> dF;
  private static final arq<Float> dG;
  private static final arq<Boolean> dH;
  private static final arq<Boolean> dI;
  private static final arq<String> dJ;
  private static final arq<Boolean> dK;
  private static final arq<String> dL;
  private static final arq<String> dM;
  private static final arq<String> dN;
  private static final arq<Boolean> dO;
  private static final arq<Integer> dP;
  private static final arq<String> dQ;
  private static final arq<Boolean> dR;
  private static final arq<Boolean> dS;
  private static final arq<String> dT;
  private static final arq<Integer> dU;
  private static final arq<Integer> dV;
  private static final arq<Integer> dW;
  private static final arq<Boolean> dX;
  private static final arq<Boolean> dY;
  private static final arq<Boolean> dZ;
  public static final arq<Integer> da;
  public static final arq<Boolean> db;
  public static final arq<Boolean> dc;
  public static final arq<Boolean> dd;
  public static final arq<Boolean> de;
  public static final arq<Integer> df;
  public static final arq<Boolean> dg;
  public static final arq<Boolean> dh;
  public static final arq<Long> di = arq.a(1, "gads:mobius_linking:sdk_side_cooldown_time_threshold:ms", 3600000L);
  public static final arq<String> dj = arq.a(0, "gads:public_beta:traffic_multiplier", "1.0");
  public static final arq<Boolean> dk = arq.a(1, "gads:real_test_request:enabled", Boolean.valueOf(true));
  public static final arq<Boolean> dl = arq.a(1, "gads:real_test_request:render_webview_label", Boolean.valueOf(true));
  public static final arq<Boolean> dm = arq.a(1, "gads:real_test_request:render_native_label", Boolean.valueOf(true));
  public static final arq<Integer> dn = arq.a(1, "gads:adoverlay:b68684796:targeting_sdk:lower_bound", 27);
  public static final arq<Integer> jdField_do = arq.a(1, "gads:adoverlay:b68684796:targeting_sdk:upper_bound", 27);
  public static final arq<Integer> dp = arq.a(1, "gads:adoverlay:b68684796:sdk_int:lower_bound", 26);
  public static final arq<Integer> dq = arq.a(1, "gads:adoverlay:b68684796:sdk_int:upper_bound", 27);
  private static final arq<String> dr = arq.a(0, "gads:sdk_core_experiment_id");
  private static final arq<String> ds;
  private static final arq<Boolean> dt;
  private static final arq<String> du;
  private static final arq<Boolean> dv;
  private static final arq<String> dw;
  private static final arq<String> dx;
  private static final arq<String> dy;
  private static final arq<Integer> dz;
  public static final arq<String> e;
  private static final arq<Long> eA;
  private static final arq<Boolean> eB;
  private static final arq<Long> eC;
  private static final arq<Long> eD;
  private static final arq<Boolean> eE;
  private static final arq<Boolean> eF;
  private static final arq<String> eG;
  private static final arq<Boolean> eH;
  private static final arq<String> eI;
  private static final arq<Boolean> eJ;
  private static final arq<Boolean> eK;
  private static final arq<String> eL;
  private static final arq<Boolean> eM;
  private static final arq<String> eN;
  private static final arq<Boolean> eO;
  private static final arq<Boolean> eP;
  private static final arq<Boolean> eQ;
  private static final arq<Boolean> eR;
  private static final arq<Boolean> eS;
  private static final arq<Boolean> eT;
  private static final arq<Boolean> eU;
  private static final arq<Boolean> eV;
  private static byte[] eW;
  private static final arq<Boolean> ea;
  private static final arq<String> eb;
  private static final arq<Long> ec;
  private static final arq<Long> ed;
  private static final arq<Boolean> ee;
  private static final arq<Boolean> ef;
  private static final arq<String> eg;
  private static final arq<String> eh;
  private static final arq<Boolean> ei;
  private static final arq<String> ej;
  private static final arq<String> ek;
  private static final arq<String> el;
  private static final arq<Boolean> em;
  private static final arq<String> en;
  private static final arq<String> eo;
  private static final arq<Long> ep;
  private static final arq<String> eq;
  private static final arq<String> er;
  private static final arq<String> es;
  private static final arq<Boolean> et;
  private static final arq<Boolean> eu;
  private static final arq<Boolean> ev;
  private static final arq<String> ew;
  private static final arq<Long> ex;
  private static final arq<Integer> ey;
  private static final arq<Integer> ez;
  public static final arq<Float> f;
  public static final arq<Boolean> g;
  public static final arq<String> h;
  public static final arq<Integer> i;
  public static final arq<Integer> j;
  public static final arq<Integer> k;
  public static final arq<Integer> l;
  public static final arq<Integer> m;
  public static final arq<Integer> n;
  public static final arq<Integer> o;
  public static final arq<Integer> p;
  public static final arq<Long> q;
  public static final arq<Long> r;
  public static final arq<Integer> s;
  public static final arq<Boolean> t;
  public static final arq<String> u;
  public static final arq<Long> v;
  public static final arq<Boolean> w;
  public static final arq<Long> x;
  public static final arq<Boolean> y;
  public static final arq<Integer> z;
  
  static
  {
    a = arq.a(0, "gads:sdk_core_location", "https://googleads.g.doubleclick.net/mads/static/mad/sdk/native/sdk-core-v40.html");
    ds = arq.a(0, "gads:sdk_core_js_location", "https://googleads.g.doubleclick.net/mads/static/mad/sdk/native/production/sdk-core-v40-impl.js");
    dt = arq.a(0, "gads:request_builder:singleton_webview", Boolean.valueOf(false));
    du = arq.a(0, "gads:request_builder:singleton_webview_experiment_id");
    dv = arq.a(0, "gads:sdk_use_dynamic_module", Boolean.valueOf(true));
    dw = arq.a(0, "gads:sdk_use_dynamic_module_experiment_id");
    b = arq.a(0, "gads:sdk_crash_report_enabled", Boolean.valueOf(false));
    c = arq.a(0, "gads:report_dynamite_crash_in_background_thread", Boolean.valueOf(false));
    d = arq.a(0, "gads:sdk_crash_report_full_stacktrace", Boolean.valueOf(false));
    e = arq.a(0, "gads:sdk_crash_report_class_prefix", "com.google.");
    f = arq.a(1, "gads:trapped_exception_sample_rate", 0.01F);
    g = arq.a(0, "gads:block_autoclicks", Boolean.valueOf(false));
    dx = arq.a(0, "gads:block_autoclicks_experiment_id");
    dy = arq.a(0, "gads:spam_app_context:experiment_id");
    dz = arq.a(1, "gads:http_url_connection_factory:timeout_millis", 10000);
    h = arq.a(1, "gads:video_exo_player:version", "1");
    i = arq.a(1, "gads:video_exo_player:connect_timeout", 8000);
    j = arq.a(1, "gads:video_exo_player:read_timeout", 8000);
    k = arq.a(1, "gads:video_exo_player:loading_check_interval", 1048576);
    l = arq.a(1, "gads:video_exo_player:exo_player_precache_limit", 2147483647);
    m = arq.a(1, "gads:video_exo_player:byte_buffer_precache_limit", 2147483647);
    dA = arq.a(0, "gads:video_stream_cache:experiment_id");
    n = arq.a(1, "gads:video_stream_cache:limit_count", 5);
    o = arq.a(1, "gads:video_stream_cache:limit_space", 8388608);
    p = arq.a(1, "gads:video_stream_exo_cache:buffer_size", 8388608);
    q = arq.a(1, "gads:video_stream_cache:limit_time_sec", 300L);
    r = arq.a(1, "gads:video_stream_cache:notify_interval_millis", 125L);
    s = arq.a(1, "gads:video_stream_cache:connect_timeout_millis", 10000);
    t = arq.a(0, "gads:video:metric_reporting_enabled", Boolean.valueOf(false));
    u = arq.a(1, "gads:video:metric_frame_hash_times", "");
    v = arq.a(1, "gads:video:metric_frame_hash_time_leniency", 500L);
    w = arq.a(1, "gads:video:force_watermark", Boolean.valueOf(false));
    x = arq.a(1, "gads:video:surface_update_min_spacing_ms", 1000L);
    y = arq.a(1, "gads:video:spinner:enabled", Boolean.valueOf(false));
    z = arq.a(1, "gads:video:spinner:scale", 4);
    A = arq.a(1, "gads:video:spinner:jank_threshold_ms", 50L);
    B = arq.a(1, "gads:video:aggressive_media_codec_release", Boolean.valueOf(false));
    C = arq.a(1, "gads:memory_bundle:debug_info", Boolean.valueOf(false));
    D = arq.a(1, "gads:memory_bundle:runtime_info", Boolean.valueOf(true));
    E = arq.a(1, "gads:video:codec_query_mime_types", "");
    F = arq.a(1, "gads:video:codec_query_minimum_version", 16);
    dB = arq.a(0, "gads:ad_id_app_context:enabled", Boolean.valueOf(false));
    dC = arq.a(0, "gads:ad_id_app_context:ping_ratio", 0.0F);
    dD = arq.a(0, "gads:ad_id_app_context:experiment_id");
    dE = arq.a(0, "gads:ad_id_use_shared_preference:experiment_id");
    dF = arq.a(0, "gads:ad_id_use_shared_preference:enabled", Boolean.valueOf(false));
    dG = arq.a(0, "gads:ad_id_use_shared_preference:ping_ratio", 0.0F);
    dH = arq.a(0, "gads:ad_id_use_persistent_service:enabled", Boolean.valueOf(false));
    dI = arq.a(0, "gads:ad_id:use_ipc:enabled", Boolean.valueOf(false));
    dJ = arq.b(0, "gads:looper_for_gms_client:experiment_id");
    G = arq.a(0, "gads:looper_for_gms_client:enabled", Boolean.valueOf(true));
    H = arq.a(0, "gads:sw_ad_request_service:enabled", Boolean.valueOf(true));
    dK = arq.a(0, "gads:sw_dynamite:enabled", Boolean.valueOf(true));
    I = arq.a(1, "gad:mraid:url_banner", "https://googleads.g.doubleclick.net/mads/static/mad/sdk/native/mraid/v2/mraid_app_banner.js");
    J = arq.a(1, "gad:mraid:url_expanded_banner", "https://googleads.g.doubleclick.net/mads/static/mad/sdk/native/mraid/v2/mraid_app_expanded_banner.js");
    K = arq.a(1, "gad:mraid:url_interstitial", "https://googleads.g.doubleclick.net/mads/static/mad/sdk/native/mraid/v2/mraid_app_interstitial.js");
    L = arq.a(1, "gad:mraid:version", "2.0");
    M = arq.a(1, "gads:mraid:unload", Boolean.valueOf(false));
    N = arq.a(0, "gads:enabled_sdk_csi", Boolean.valueOf(false));
    O = arq.a(0, "gads:sdk_csi_server", "https://csi.gstatic.com/csi");
    P = arq.a(0, "gads:sdk_csi_write_to_file", Boolean.valueOf(false));
    Q = arq.a(0, "gads:enable_content_fetching", Boolean.valueOf(true));
    R = arq.a(0, "gads:content_length_weight", 1);
    S = arq.a(0, "gads:content_age_weight", 1);
    T = arq.a(0, "gads:min_content_len", 11);
    U = arq.a(0, "gads:fingerprint_number", 10);
    V = arq.a(0, "gads:sleep_sec", 10);
    W = arq.a(1, "gads:enable_content_url_hash", Boolean.valueOf(true));
    X = arq.a(1, "gads:content_vertical_fingerprint_number", 100);
    Y = arq.a(1, "gads:enable_content_vertical_hash", Boolean.valueOf(true));
    Z = arq.a(1, "gads:content_vertical_fingerprint_bits", 23);
    aa = arq.a(1, "gads:content_vertical_fingerprint_ngram", 3);
    ab = arq.a(1, "gads:content_fetch_view_tag_id", "googlebot");
    ac = arq.a(1, "gads:content_fetch_exclude_view_tag", "none");
    ad = arq.a(0, "gad:app_index_enabled", Boolean.valueOf(true));
    ae = arq.a(1, "gads:content_fetch_disable_get_title_from_webview", Boolean.valueOf(false));
    af = arq.a(0, "gads:app_index:without_content_info_present:enabled", Boolean.valueOf(true));
    ag = arq.a(0, "gads:app_index:timeout_ms", 1000L);
    dL = arq.a(0, "gads:app_index:experiment_id");
    dM = arq.a(0, "gads:kitkat_interstitial_workaround:experiment_id");
    ah = arq.a(0, "gads:kitkat_interstitial_workaround:enabled", Boolean.valueOf(true));
    ai = arq.a(0, "gads:interstitial_follow_url", Boolean.valueOf(true));
    aj = arq.a(0, "gads:interstitial_follow_url:register_click", Boolean.valueOf(true));
    dN = arq.a(0, "gads:interstitial_follow_url:experiment_id");
    dO = arq.a(0, "gads:analytics_enabled", Boolean.valueOf(true));
    ak = arq.a(0, "gads:ad_key_enabled", Boolean.valueOf(false));
    al = arq.a(1, "gads:sai:enabled", Boolean.valueOf(true));
    am = arq.a(1, "gads:sai:banner_ad_enabled", Boolean.valueOf(true));
    an = arq.a(1, "gads:sai:native_ad_enabled", Boolean.valueOf(true));
    ao = arq.a(1, "gads:sai:interstitial_ad_enabled", Boolean.valueOf(true));
    ap = arq.a(1, "gads:sai:rewardedvideo_ad_enabled", Boolean.valueOf(true));
    aq = arq.a(1, "gads:sai:click_ping_schema_v2", "^[^?]*(/aclk\\?|/pcs/click\\?).*");
    ar = arq.a(1, "gads:sai:impression_ping_schema_v2", "^[^?]*/adview.*");
    as = arq.a(1, "gads:sai:click_gmsg_enabled", Boolean.valueOf(true));
    at = arq.a(1, "gads:sai:using_macro:enabled", Boolean.valueOf(false));
    au = arq.a(1, "gads:sai:ad_event_id_macro_name", "[gw_fbsaeid]");
    av = arq.a(1, "gads:sai:timeout_ms", -1L);
    aw = arq.a(1, "gads:sai:scion_thread_pool_size", 5);
    ax = arq.a(1, "gads:x_seconds_rewarded:enable", Boolean.valueOf(false));
    dP = arq.a(0, "gads:webview_cache_version", 0);
    ay = arq.a(1, "gads:webview:ignore_over_scroll", Boolean.valueOf(true));
    az = arq.a(0, "gads:corewebview:adwebview_factory:enable", Boolean.valueOf(false));
    aA = arq.a(0, "gads:corewebview:javascript_engine", Boolean.valueOf(false));
    aB = arq.a(1, "gad:webview:inject_scripts", Boolean.valueOf(false));
    aC = arq.a(0, "gads:webview:permission:disabled", Boolean.valueOf(false));
    dQ = arq.b(0, "gads:pan:experiment_id");
    aD = arq.a(1, "gads:rewarded:adapter_initialization_enabled", Boolean.valueOf(false));
    aE = arq.a(1, "gads:rewarded:adapter_timeout_ms", 20000L);
    aF = arq.a(1, "gads:rewarded:ad_metadata_enabled", Boolean.valueOf(false));
    aG = arq.a(1, "gads:app_activity_tracker:enabled", Boolean.valueOf(true));
    aH = arq.a(1, "gads:app_activity_tracker:notify_background_listeners_delay_ms", 500L);
    aI = arq.a(1, "gads:app_activity_tracker:app_session_timeout_ms", TimeUnit.MINUTES.toMillis(5L));
    aJ = arq.a(1, "gads:adid_values_in_adrequest:enabled", Boolean.valueOf(false));
    aK = arq.a(1, "gads:adid_values_in_adrequest:timeout", 2000L);
    aL = arq.a(1, "gads:disable_adid_values_in_ms", Boolean.valueOf(false));
    aM = arq.a(1, "gads:enable_ad_loader_manager", Boolean.valueOf(true));
    dR = arq.a(0, "gads:ad_serving:enabled", Boolean.valueOf(true));
    aN = arq.a(1, "gads:ad_manager_enforce_arp_invariant:enabled", Boolean.valueOf(true));
    aO = arq.a(1, "gads:ad_manager:admob_extra:new_bundle", Boolean.valueOf(true));
    aP = arq.a(1, "gads:ad_overlay:delay_page_close_timeout_ms", 5000L);
    aQ = arq.a(1, "gads:interstitial_ad_immersive_mode", Boolean.valueOf(true));
    aR = arq.a(1, "gads:custom_close_blocking:enabled", Boolean.valueOf(false));
    aS = arq.a(1, "gads:disabling_closable_area:enabled", Boolean.valueOf(false));
    dS = arq.a(1, "gads:impression_optimization_enabled", Boolean.valueOf(false));
    dT = arq.a(1, "gads:banner_ad_pool:schema", "customTargeting");
    dU = arq.a(1, "gads:banner_ad_pool:max_queues", 3);
    dV = arq.a(1, "gads:banner_ad_pool:max_pools", 3);
    aT = arq.a(1, "gads:interstitial_ad_pool:enabled", Boolean.valueOf(false));
    aU = arq.a(1, "gads:interstitial_ad_pool:enabled_for_rewarded", Boolean.valueOf(false));
    aV = arq.a(1, "gads:interstitial_ad_pool:schema", "customTargeting");
    aW = arq.a(1, "gads:interstitial_ad_pool:request_exclusions", "com.google.ads.mediation.admob.AdMobAdapter/_ad");
    aX = arq.a(1, "gads:interstitial_ad_pool:max_pools", 3);
    aY = arq.a(1, "gads:interstitial_ad_pool:max_pool_depth", 2);
    aZ = arq.a(1, "gads:interstitial_ad_pool:time_limit_sec", 1200);
    ba = arq.a(1, "gads:interstitial_ad_pool:ad_unit_exclusions", "(?!)");
    bb = arq.a(1, "gads:interstitial_ad_pool:top_off_latency_min_millis", 0);
    bc = arq.a(1, "gads:interstitial_ad_pool:top_off_latency_range_millis", 0);
    bd = arq.a(1, "gads:interstitial_ad_pool:discard_thresholds", 0L);
    be = arq.a(1, "gads:interstitial_ad_pool:miss_thresholds", 0L);
    bf = arq.a(1, "gads:interstitial_ad_pool:discard_asymptote", 0.0F);
    bg = arq.a(1, "gads:interstitial_ad_pool:miss_asymptote", 0.0F);
    bh = arq.a(0, "gads:debug_logging_feature:enable", Boolean.valueOf(false));
    bi = arq.a(0, "gads:debug_logging_feature:intercept_web_view", Boolean.valueOf(false));
    dW = arq.a(1, "gads:heap_wastage:bytes", 0);
    bj = arq.a(1, "gads:spherical_video:vertex_shader", "");
    bk = arq.a(1, "gads:spherical_video:fragment_shader", "");
    bl = arq.a(0, "gads:log:verbose_enabled", Boolean.valueOf(false));
    bm = arq.a(1, "gads:include_local_global_rectangles", Boolean.valueOf(false));
    bn = arq.a(1, "gads:position_watcher:throttle_ms", 200L);
    bo = arq.a(1, "gads:include_lock_screen_apps_for_visibility", Boolean.valueOf(true));
    bp = arq.a(0, "gads:device_info_caching:enabled", Boolean.valueOf(true));
    bq = arq.a(0, "gads:device_info_caching_expiry_ms:expiry", 300000L);
    br = arq.a(1, "gads:gen204_signals:enabled", Boolean.valueOf(false));
    bs = arq.a(0, "gads:webview:error_reporting_enabled", Boolean.valueOf(false));
    dX = arq.a(0, "gads:adid_reporting:enabled", Boolean.valueOf(false));
    dY = arq.a(0, "gads:ad_settings_page_reporting:enabled", Boolean.valueOf(false));
    dZ = arq.a(0, "gads:adid_info_gmscore_upgrade_reporting:enabled", Boolean.valueOf(false));
    ea = arq.a(0, "gads:request_pkg:enabled", Boolean.valueOf(true));
    bt = arq.a(1, "gads:gmsg:disable_back_button:enabled", Boolean.valueOf(true));
    bu = arq.a(0, "gads:gmsg:video_meta:enabled", Boolean.valueOf(true));
    eb = arq.a(0, "gads:gmsg:video_meta:experiment_id");
    ec = arq.a(1, "gads:network:cache_prediction_duration_s", 300L);
    bv = arq.a(1, "gads:network:network_prediction_timeout_ms", 2000L);
    bw = arq.a(0, "gads:mediation:dynamite_first:admobadapter", Boolean.valueOf(true));
    bx = arq.a(0, "gads:mediation:dynamite_first:adurladapter", Boolean.valueOf(true));
    by = arq.a(1, "gads:bypass_adrequest_service_for_inlined_mediation", Boolean.valueOf(true));
    ed = arq.a(1, "gads:rtb_signal_timeout_ms", 1000L);
    bz = arq.a(0, "gads:resolve_future:default_timeout_ms", 30000L);
    bA = arq.a(0, "gads:ad_loader:timeout_ms", 60000L);
    bB = arq.a(0, "gads:rendering:timeout_ms", 60000L);
    bC = arq.a(0, "gads:adshield:enable_adshield_instrumentation", Boolean.valueOf(false));
    bD = arq.a(1, "gads:gestures:task_timeout", 2000L);
    bE = arq.a(1, "gads:gestures:asig:enabled", Boolean.valueOf(false));
    bF = arq.a(1, "gads:gestures:ans:enabled", Boolean.valueOf(false));
    bG = arq.a(1, "gads:gestures:tos:enabled", Boolean.valueOf(false));
    bH = arq.a(1, "gads:signal:app_permissions:disabled", Boolean.valueOf(false));
    bI = arq.a(1, "gads:gestures:inthex:enabled", Boolean.valueOf(false));
    bJ = arq.a(1, "gads:gestures:hpk:enabled", Boolean.valueOf(true));
    bK = arq.a(1, "gads:gestures:pk", "");
    bL = arq.a(1, "gads:gestures:bs:enabled", Boolean.valueOf(true));
    bM = arq.a(1, "gads:gestures:check_initialization_thread:enabled", Boolean.valueOf(false));
    bN = arq.a(1, "gads:gestures:get_query_in_non_ui_thread:enabled", Boolean.valueOf(true));
    bO = arq.a(0, "gass:enabled", Boolean.valueOf(true));
    bP = arq.a(0, "gass:enable_int_signal", Boolean.valueOf(true));
    bQ = arq.a(0, "gass:enable_ad_attestation_signal", Boolean.valueOf(true));
    ee = arq.a(0, "gads:adid_notification:first_party_check:enabled", Boolean.valueOf(true));
    ef = arq.a(0, "gads:edu_device_helper:enabled", Boolean.valueOf(true));
    bR = arq.a(0, "gads:support_screen_shot", Boolean.valueOf(true));
    bS = arq.a(0, "gads:use_get_drawing_cache_for_screenshot:enabled", Boolean.valueOf(true));
    eg = arq.a(0, "gads:use_get_drawing_cache_for_screenshot:experiment_id");
    eh = arq.a(1, "gads:sdk_core_constants:experiment_id");
    bT = arq.a(1, "gads:sdk_core_constants:caps", "");
    bU = arq.a(0, "gads:js_flags:update_interval", TimeUnit.HOURS.toMillis(12L));
    bV = arq.a(0, "gads:js_flags:mf", Boolean.valueOf(false));
    ei = arq.a(1, "gads:js_flags:disable_phenotype", Boolean.valueOf(false));
    bW = arq.a(0, "gads:custom_render:ping_on_ad_rendered", Boolean.valueOf(false));
    bX = arq.a(1, "gads:native:engine_url_with_protocol", "https://googleads.g.doubleclick.net/mads/static/mad/sdk/native/native_ads.html");
    ej = arq.a(0, "gads:native:engine_js_url_with_protocol", "https://googleads.g.doubleclick.net/mads/static/mad/sdk/native/production/native_ads.js");
    ek = arq.a(1, "gads:native:video_url", "//imasdk.googleapis.com/admob/sdkloader/native_video.html");
    bY = arq.a(1, "gads:native:video_url_with_protocol", "https://imasdk.googleapis.com/admob/sdkloader/native_video.html");
    el = arq.a(1, "gads:singleton_webview_native:experiment_id");
    bZ = arq.a(1, "gads:enable_untrack_view_native", Boolean.valueOf(true));
    ca = arq.a(1, "gads:ignore_untrack_view_google_native", Boolean.valueOf(true));
    cb = arq.a(1, "gads:reset_listeners_preparead_native", Boolean.valueOf(true));
    cc = arq.a(1, "gads:native_video_load_timeout", 10);
    cd = arq.a(1, "gads:omid:native_webview_load_timeout", 2000);
    ce = arq.a(1, "gads:ad_choices_content_description", "Ad Choices Icon");
    cf = arq.a(1, "gads:clamp_native_video_player_dimensions", Boolean.valueOf(true));
    cg = arq.a(1, "gads:enable_store_active_view_state", Boolean.valueOf(false));
    ch = arq.a(1, "gads:enable_singleton_broadcast_receiver", Boolean.valueOf(false));
    ci = arq.a(1, "gads:native:overlay_new_fix:enabled", Boolean.valueOf(true));
    cj = arq.a(1, "gads:native:count_impression_for_assets", Boolean.valueOf(false));
    ck = arq.a(1, "gads:native:custom_one_point_five_click:enable", Boolean.valueOf(true));
    cl = arq.a(1, "gads:unified_native_ad:enable", Boolean.valueOf(true));
    cm = arq.a(1, "gads:fluid_ad:use_wrap_content_height", Boolean.valueOf(false));
    cn = arq.a(0, "gads:method_tracing:enabled", Boolean.valueOf(false));
    co = arq.a(0, "gads:method_tracing:duration_ms", 30000L);
    cp = arq.a(0, "gads:method_tracing:count", 5);
    cq = arq.a(0, "gads:method_tracing:filesize", 134217728);
    em = arq.a(1, "gads:auto_location_for_coarse_permission", Boolean.valueOf(false));
    en = arq.b(1, "gads:auto_location_for_coarse_permission:experiment_id");
    cr = arq.a(1, "gads:auto_location_timeout", 2000L);
    eo = arq.b(1, "gads:auto_location_timeout:experiment_id");
    ep = arq.a(1, "gads:auto_location_interval", -1L);
    eq = arq.b(1, "gads:auto_location_interval:experiment_id");
    cs = arq.a(1, "gads:fetch_app_settings_using_cld:enabled", Boolean.valueOf(false));
    er = arq.a(1, "gads:fetch_app_settings_using_cld:enabled:experiment_id");
    ct = arq.a(1, "gads:fetch_app_settings_using_cld:refresh_interval_ms", 7200000L);
    es = arq.a(0, "gads:afs:csa:experiment_id");
    cu = arq.a(0, "gads:afs:csa_webview_gmsg_ad_failed", "gmsg://noAdLoaded");
    cv = arq.a(0, "gads:afs:csa_webview_gmsg_script_load_failed", "gmsg://scriptLoadFailed");
    cw = arq.a(0, "gads:afs:csa_webview_gmsg_ad_loaded", "gmsg://adResized");
    cx = arq.a(0, "gads:afs:csa_webview_static_file_path", "/afs/ads/i/webview.html");
    cy = arq.a(0, "gads:afs:csa_webview_custom_domain_param_key", "csa_customDomain");
    cz = arq.a(0, "gads:afs:csa_webview_adshield_timeout_ms", 1000L);
    et = arq.a(0, "gads:afs:csa_ad_manager_enabled", Boolean.valueOf(true));
    eu = arq.a(1, "gads:parental_controls:send_from_client", Boolean.valueOf(true));
    ev = arq.a(1, "gads:parental_controls:cache_results", Boolean.valueOf(true));
    cA = arq.a(1, "gads:parental_controls:timeout", 2000L);
    ew = arq.a(0, "gads:safe_browsing:api_key", "AIzaSyDRKQ9d6kfsoZT2lUnZcZnBYvH69HExNPE");
    ex = arq.a(0, "gads:safe_browsing:safety_net:delay_ms", 2000L);
    cB = arq.a(0, "gads:safe_browsing:debug", Boolean.valueOf(false));
    cC = arq.a(0, "gads:webview_cookie:enabled", Boolean.valueOf(true));
    ey = arq.a(1, "gads:cache:ad_request_timeout_millis", 250);
    ez = arq.a(1, "gads:cache:max_concurrent_downloads", 10);
    eA = arq.a(1, "gads:cache:javascript_timeout_millis", 5000L);
    cD = arq.a(1, "gads:cache:bind_on_foreground", Boolean.valueOf(false));
    cE = arq.a(1, "gads:cache:bind_on_init", Boolean.valueOf(false));
    cF = arq.a(1, "gads:cache:bind_on_request", Boolean.valueOf(false));
    cG = arq.a(1, "gads:cache:bind_on_request_keep_alive", TimeUnit.SECONDS.toMillis(30L));
    cH = arq.a(1, "gads:cache:use_cache_data_source", Boolean.valueOf(false));
    eB = arq.a(1, "gads:cache:connection_per_read", Boolean.valueOf(false));
    eC = arq.a(1, "gads:cache:connection_timeout", 5000L);
    eD = arq.a(1, "gads:cache:read_only_connection_timeout", 5000L);
    cI = arq.a(1, "gads:http_assets_cache:enabled", Boolean.valueOf(false));
    cJ = arq.a(1, "gads:http_assets_cache:regex", "(?i)https:\\/\\/(tpc\\.googlesyndication\\.com\\/(.*)|lh\\d+\\.googleusercontent\\.com\\/(.*))");
    cK = arq.a(1, "gads:http_assets_cache:time_out", 100);
    cL = arq.a(1, "gads:chrome_custom_tabs:enabled", Boolean.valueOf(true));
    cM = arq.a(1, "gads:chrome_custom_tabs_browser:enabled", Boolean.valueOf(false));
    cN = arq.a(1, "gads:chrome_custom_tabs:disabled", Boolean.valueOf(false));
    cO = arq.a(1, "gads:drx_in_app_preview:enabled", Boolean.valueOf(true));
    cP = arq.a(1, "gads:drx_debug_signals:enabled", Boolean.valueOf(true));
    cQ = arq.a(1, "gads:debug_hold_gesture:enabled", Boolean.valueOf(false));
    cR = arq.a(1, "gads:debug_hold_gesture:time_millis", 2000L);
    cS = arq.a(1, "gads:drx_debug:debug_device_linking_url", "https://www.google.com/dfp/linkDevice");
    cT = arq.a(1, "gads:drx_debug:in_app_preview_status_url", "https://www.google.com/dfp/inAppPreview");
    cU = arq.a(1, "gads:drx_debug:debug_signal_status_url", "https://www.google.com/dfp/debugSignals");
    cV = arq.a(1, "gads:drx_debug:send_debug_data_url", "https://www.google.com/dfp/sendDebugData");
    cW = arq.a(1, "gads:drx_debug:timeout_ms", 5000);
    cX = arq.a(1, "gad:pixel_dp_comparision_multiplier", 1);
    cY = arq.a(1, "gad:interstitial_for_multi_window", Boolean.valueOf(false));
    cZ = arq.a(1, "gad:interstitial_ad_stay_active_in_multi_window", Boolean.valueOf(false));
    da = arq.a(1, "gad:interstitial:close_button_padding_dip", 0);
    db = arq.a(1, "gads:clearcut_logging:enabled", Boolean.valueOf(false));
    dc = arq.a(1, "gads:clearcut_logging:write_to_file", Boolean.valueOf(false));
    dd = arq.a(0, "gad:force_local_ad_request_service:enabled", Boolean.valueOf(false));
    de = arq.a(0, "gad:force_dynamite_loading_enabled", Boolean.valueOf(false));
    df = arq.a(1, "gad:http_redirect_max_count:times", 8);
    dg = arq.a(1, "gads:omid:enabled", Boolean.valueOf(false));
    eE = arq.a(0, "gads:nonagon:red_button", Boolean.valueOf(false));
    eF = arq.a(1, "gads:nonagon:banner:enabled", Boolean.valueOf(false));
    eG = arq.a(1, "gads:nonagon:banner:ad_unit_exclusions", "(?!)");
    eH = arq.a(1, "gads:nonagon:interstitial:enabled", Boolean.valueOf(false));
    eI = arq.a(1, "gads:nonagon:interstitial:ad_unit_exclusions", "(?!)");
    eJ = arq.a(1, "gads:nonagon:rewardedvideo:enabled", Boolean.valueOf(false));
    eK = arq.a(1, "gads:nonagon:mobile_ads_setting_manager:enabled", Boolean.valueOf(false));
    eL = arq.a(1, "gads:nonagon:rewardedvideo:ad_unit_exclusions", "(?!)");
    eM = arq.a(1, "gads:nonagon:nativead:enabled", Boolean.valueOf(false));
    eN = arq.a(1, "gads:nonagon:nativead:app_name", "(?!)");
    dh = arq.a(1, "gads:nonagon:banner:check_dp_size", Boolean.valueOf(false));
    eO = arq.a(1, "gads:nonagon:service:enabled", Boolean.valueOf(false));
    eP = arq.a(1, "gads:signals:ad_id_info:enabled", Boolean.valueOf(false));
    eQ = arq.a(1, "gads:signals:app_index:enabled", Boolean.valueOf(false));
    eR = arq.a(1, "gads:signals:cache:enabled", Boolean.valueOf(false));
    eS = arq.a(1, "gads:signals:doritos:enabled", Boolean.valueOf(false));
    eT = arq.a(1, "gads:signals:location:enabled", Boolean.valueOf(false));
    eU = arq.a(1, "gads:signals:network_prediction:enabled", Boolean.valueOf(false));
    eV = arq.a(1, "gads:signals:parental_control:enabled", Boolean.valueOf(false));
  }
  
  public static List<String> a()
  {
    return aos.e().a();
  }
  
  public static void a(Context paramContext)
  {
    lq.a(paramContext, new asb(paramContext));
    arq localarq = dW;
    int i1 = ((Integer)aos.f().a(localarq)).intValue();
    if ((i1 > 0) && (eW == null)) {
      eW = new byte[i1];
    }
  }
  
  public static void a(Context paramContext, int paramInt, JSONObject paramJSONObject)
  {
    aos.d();
    SharedPreferences.Editor localEditor = paramContext.getSharedPreferences("google_ads_flags", 0).edit();
    aos.e().a(localEditor, 1, paramJSONObject);
    aos.d();
    localEditor.commit();
  }
  
  public static List<String> b()
  {
    return aos.e().b();
  }
}


/* Location:           C:\Users\IrfanRZ\Desktop\video walp\classes_dex2jar.jar
 * Qualified Name:     com.google.android.gms.internal.ads.asa
 * JD-Core Version:    0.7.0.1
 */